DATASET:
  DATA_SET: hn3
  CATEGORY_NUM: 2
  CROP_SIZE: 16
  PATCHES_NUM: 400
  TRAIN_NUM: 12750
  VAL_NUM: 4250
SEARCH:
  SEARCH_ON: True
  ARCH_START_EPOCH: 30
MODEL:
  META_ARCHITECTURE: searchnet
  AFFINE: False
DATALOADER:
  BATCH_SIZE_TRAIN: 2
  BATCH_SIZE_TEST: 2
  NUM_WORKERS: 4
  DATA_LIST_DIR: ./sample
SOLVER:
  MAX_EPOCH: 150
  CHECKPOINT_PERIOD: 1

OUTPUT_DIR: output
