DATASET:
  DATA_SET: gd4
  CATEGORY_NUM: 2
  CROP_SIZE: 14
  PATCHES_NUM: 400
  TRAIN_NUM: 22500
  VAL_NUM: 7500
SEARCH:
  SEARCH_ON: True
  ARCH_START_EPOCH: 1
MODEL:
  META_ARCHITECTURE: searchnet
  AFFINE: False
DATALOADER:
  BATCH_SIZE_TRAIN: 1
  BATCH_SIZE_TEST: 1
  NUM_WORKERS: 4
  DATA_LIST_DIR: ./sample
SOLVER:
  MAX_EPOCH: 2
  CHECKPOINT_PERIOD: 1

OUTPUT_DIR: output
